# Generated by Django 5.2.1 on 2025-06-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="default_profile1.jpg",
                null=True,
                upload_to="profile_pics/",
                verbose_name="Immagine profilo",
            ),
        ),
    ]
