# Generated by Django 5.2.1 on 2025-06-08 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_category_options_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="requires_size",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("description", models.CharField(blank=True, max_length=50)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=models.ManyToManyField(blank=True, to="shop.size"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["requires_size"], name="shop_produc_require_2e4564_idx"
            ),
        ),
    ]
