# Generated by Django 5.2.1 on 2025-06-11 20:52

import uuid
from django.db import migrations, models

def generate_codes(apps, schema_editor):
    Order = apps.get_model('shop', 'Order')
    for order in Order.objects.all():
        if not order.code:
            order.code = str(uuid.uuid4())
            order.save()

class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_orderitem_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="code",
            field=models.CharField(
                max_length=36,
                editable=False,
                default='',
            ),
            preserve_default=False,
        ),
        migrations.RunPython(generate_codes),
    ]