# Generated by Django 5.2.1 on 2025-06-11 20:58
import uuid
from django.db import migrations

def generate_codes(apps, schema_editor):
    Order = apps.get_model('shop', 'Order')
    for order in Order.objects.all():
        order.code = str(uuid.uuid4())
        order.save()

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_code'),
    ]

    operations = [
        migrations.RunPython(generate_codes),
    ]
