# Generated by Django 5.2.1 on 2025-06-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_auto_20250611_2258"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(editable=False, max_length=36, unique=True),
        ),
    ]
