# Generated by Django 5.2.1 on 2025-06-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_postal_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
