# Generated by Django 5.2.1 on 2025-06-20 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_product_sold_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="sold_count",
            new_name="total_sold",
        ),
    ]
