# Generated by Django 5.2.1 on 2025-06-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_rename_sold_count_product_total_sold"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="material",
        ),
        migrations.AddField(
            model_name="product",
            name="materials",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="shop.material"
            ),
        ),
    ]
