# Generated by Django 5.2.1 on 2025-06-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_material_remove_product_material_product_materials"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="type",
            field=models.CharField(
                choices=[("MT", "Metallo"), ("GS", "Pietra"), ("OR", "Organico")],
                default="MT",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
