# Generated by Django 5.2.1 on 2025-06-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_material_type_alter_material_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="materials",
            field=models.ManyToManyField(
                help_text="Seleziona almeno un materiale",
                related_name="products",
                to="shop.material",
            ),
        ),
    ]
