# Generated by Django 5.2.1 on 2025-06-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_alter_product_materials"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="orderitem",
            name="unique_order_product",
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(
                fields=("order", "product", "size"), name="unique_order_product_size"
            ),
        ),
    ]
