# Generated by Django 5.2.1 on 2025-06-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_remove_orderitem_unique_order_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cod", "Pagamento alla consegna"),
                    ("fake_card", "Carta di credito (simulato)"),
                    ("paypal", "PayPal (simulato)"),
                ],
                default="cod",
                max_length=20,
            ),
        ),
    ]
