# Generated by Django 5.2.1 on 2025-06-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_order_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cod", "Pagamento alla consegna"),
                    ("fake_card", "Carta di credito"),
                    ("paypal", "PayPal"),
                ],
                default="cod",
                max_length=20,
            ),
        ),
    ]
